// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrggqcqvtpxnmewmjpng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndyZ2dxY3F2dHB4bm1ld21qcG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1MzgyODksImV4cCI6MjA4NDExNDI4OX0.uWL-iIMzdhvO4hQ2aUBIjt1wJCW5Q8i0UwEtnJUgCAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});